name: Deploy to staging and run E2E tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
          using pnpm
        run: |
          npm install -g pnpm
          pnpm install
          npm install -g firebase-tools  # Install Firebase CLI

      - name: Create .env.staging file
        run: |
          echo "VITE_ENV=staging" >> .env.staging
          echo "VITE_EMAIL_API_URL=${{ secrets.VITE_EMAIL_API_URL }}" >> .env.staging
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY_STAGING }}" >> .env.staging
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN_STAGING }}" >> .env.staging
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID_STAGING }}" >> .env.staging
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET_STAGING }}" >> .env.staging
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID_STAGING }}" >> .env.staging
          echo "VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID_STAGING }}" >> .env.staging
          echo "VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}" >> .env.staging

      - name: Build for staging
        run: pnpm run build --mode staging

      - name: Deploy to staging
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project blui-dev
          appId: ${{ secrets.FIREBASE_APP_ID_STAGING }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS_STAGING }}
          run: firebase deploy --project blui-dev

      - name: Run e2e tests against staging
        run: pnpm run test:e2e
